/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DummyTesting;

import org.junit.Test;
import org.junit.Assert;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void givenFirstName_WhenProper_ShouldReturnTrue() {
        UserValidator validator = new UserValidator();
        boolean result = validator.validateFirstName("Prashant");
        Assert.assertEquals(true,result);
    }
}
